### ISSUE TITLE
TypeError: cannot make memory view because object does not have the buffer interface

### ISSUE THREAD

**Issue by Fale** [cyrozap/python-vipaccess#7]
After having installed it via PIP, this is what happens:

```
fale@x250:~ $ vipaccess 
Traceback (most recent call last):
  File "/usr/bin/vipaccess", line 9, in <module>
    load_entry_point('python-vipaccess==0.3.0', 'console_scripts', 'vipaccess')()
  File "/usr/lib/python2.7/site-packages/vipaccess/utils.py", line 273, in main
    response = get_provisioning_response(request)
  File "/usr/lib/python2.7/site-packages/vipaccess/utils.py", line 147, in get_provisioning_response
    return requests.post(PROVISIONING_URL, data=request)
  File "/usr/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 869, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 216, in sendall
    data = memoryview(data)
TypeError: cannot make memory view because object does not have the buffer interface
```

**Comment by cyrozap** [comment]
Closing this issue since I'm no longer maintaining this project and will be archiving it soon. Please use [this fork](https://github.com/dlenski/python-vipaccess) instead.
